server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF8
  port: 8000
  compression:
    enabled: true

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      enabled: true
      max-request-size: 3MB
      max-file-size: 3MB
  application:
    name: regista
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${api-keys.google-client-id}
            client-secret: ${api-keys.google-client-secret}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/v1/auths/oauth2/callback/{registrationId}"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

logging:
  level:
    root: WARN                # Mức log mặc định cho toàn hệ thống là WARN
    org.springframework: ERROR # Chỉ hiển thị lỗi từ Spring
    org.hibernate: ERROR      # Chỉ hiển thị lỗi từ Hibernate
    com.eventregistration: INFO

springdoc:
  swagger-ui:
    path: /api-documentation
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
    display-request-duration: true
    filter: true
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  paths-to-match: 
    - /api/**
    - /auths/**
    - /users/**
    - /events/**
    - /calendars/**

openapi:
  service:
    api-docs: api-service
    server:
      local: http://localhost:8000
      dev: https://be-event-registration-project-production.up.railway.app
    title: Event Registration API
    version: 1.0.0
    description: Comprehensive API for managing events, registrations, calendars, and users

api-keys:
  brevo: ${BREVO_APIKEY}
  pexels: ${PEXELS_APIKEY}
  translate: ${TRANSLATE_APIKEY}
  google-client-id: ${GOOGLE_CLIENT_ID}
  google-client-secret: ${GOOGLE_CLIENT_SECRET}
  facebook-client-id: ${FACEBOOK_CLIENT_ID}
  facebook-client-secret: ${FACEBOOK_CLIENT_SECRET}
  jwt-access: ${JWT_ACCESS_SIGNER_KEY}
  jwt-refresh: ${JWT_REFRESH_SIGNER_KEY}
  jwt-reset-password: ${JWT_RESET_PASSWORD_SIGNER_KEY}
  jwt-access-duration: ${JWT_ACCESS_TOKEN_DURATION:7200}
  jwt-refresh-duration: ${JWT_REFRESH_TOKEN_DURATION:604800}
  jwt-reset-password-duration: ${JWT_RESET_PASSWORD_TOKEN_DURATION:3600}
  db-url: ${DB_URL}
  db-username: ${DB_USERNAME}
  db-password: ${DB_PASSWORD}
  redis-host: ${REDIS_HOST}
  redis-port: ${REDIS_PORT}
  redis-password: ${REDIS_PASSWORD}
  sender-email: ${SENDER_EMAIL}
  sender-name: ${SENDER_NAME}
  firebase-bucket-name: ${FIREBASE_BUCKET_NAME}

app:
  email-client:
    brevo-url: ${BREVO_API_URL:https://api.brevo.com}
    brevo-apikey: ${BREVO_APIKEY}
    sender:
      email: ${SENDER_EMAIL}
      name: ${SENDER_NAME}
  dictionary-client:
    url: ${DICTIONARY_API_URL}
  pexels-client:
    url: ${PEXELS_API_URL}
    apikey: ${PEXELS_APIKEY}
  translate-client:
    url: ${TRANSLATE_API_URL}
    apikey: ${TRANSLATE_APIKEY}
  firebase:
    bucket-name: ${FIREBASE_BUCKET_NAME}

client:
  url: ${CLIENT_URL}

