name: Event Registration Backend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - src/main/java/com/eventregistration/**
      - Dockerfile
      - build.gradle
  pull_request:
    branches:
      - main
    paths:
      - src/main/java/com/eventregistration/**
      - Dockerfile
      - build.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # - name: Run tests with test profile
      #   run: ./gradlew test -Dspring.profiles.active=test

      - name: Build Docker image
        run: docker build -t kaitoudicode/event-registration:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push kaitoudicode/event-registration:latest


